name: CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the 'main' branch

jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest

    env:
        AWS_REGION: 'ap-south-1'
        TF_VERSION: '1.4.0'
    
    steps:
    - name: 'Checkout Github Repo'
      uses: actions/checkout@v2
    
    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: ${{ env.TF_VERSION }}

    - name: 'Terraform Init'
      working-directory: /home/mone/Journey/ProJs/Prep/DevOps-Task/TF-ECS-FARGATE/IaC/InfraStructure/Root
      run: terraform init

    - name: 'Terraform Format'
      working-directory: /home/mone/Journey/ProJs/Prep/DevOps-Task/TF-ECS-FARGATE/IaC/InfraStructure/Root
      run: terraform fmt

    - name: 'Terraform Validate'
      working-directory: /home/mone/Journey/ProJs/Prep/DevOps-Task/TF-ECS-FARGATE/IaC/InfraStructure/Root
      run: terraform validate

    - name: 'Check Current Directory'
      run: pwd  # This will output the current directory in the pipeline logs

    - name: 'Terraform Plan'
      working-directory: /home/mone/Journey/ProJs/Prep/DevOps-Task/TF-ECS-FARGATE/IaC/InfraStructure/Root
      run: terraform plan

    - name: 'Terraform Apply'
      working-directory: /home/mone/Journey/ProJs/Prep/DevOps-Task/TF-ECS-FARGATE/IaC/InfraStructure/Root
      if: github.ref == 'refs/heads/main'
      run: terraform apply --auto-approve
