name: Terraform Destroy
on:
  workflow_dispatch:

jobs:
  terraform-cleanup:
    name: 'Post Apply Cleanup'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'ap-south-1'
      TF_VERSION: '5.0'

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: 'Terraform Init'
      working-directory: /home/runner/work/TF-ECS-FARGATE/TF-ECS-FARGATE/IaC/InfraStructure/Root
      run: terraform init

    - name: 'Terraform Plan Destroy'
      working-directory: /home/runner/work/TF-ECS-FARGATE/TF-ECS-FARGATE/IaC/InfraStructure/Root
      run: terraform plan -destroy -out=tfplan-destroy

    - name: 'Terraform Apply Destroy'
      working-directory: /home/runner/work/TF-ECS-FARGATE/TF-ECS-FARGATE/IaC/InfraStructure/Root
      run: terraform apply -auto-approve tfplan-destroy